### ISSUE TITLE
Proposition: Disable `Style/CaseEquality`

### ISSUE THREAD

**Issue by gmalette** [Shopify/ruby-style-guide#150]
We currently have `Style/CaseEquality` cop enabled, which disallows the usage of `===`. 

In general, I agree that `===` should be discouraged (on `Enumerable`, `Regexp`, etc), but I don't think we can disallow it using Rubocop, and in at least one scenario it should actually be the encouraged way of doing things: hierarchy membership checks (aka: typechecking, but not quite).

The idiomatic way of doing hierarchy membership checking is typically using the `is_a?` or `kind_of?`, but this should actually be discouraged, for two reasons.

1. `BasicObject` doesn't respond to `is_a?` and so whenever we use `is_a?`. 
  When we use `is_a?` we introduce coupling (which is generally unnecessary), between the code that checks and the code that produces the objects. This practice is also prevented by Sorbet when using interfaces, because the implementation could very well be a `BasicObject`. In the Checkouts component, we've had to disable the check entirely since we use Sorbet with strict typing enabled. 

2. When checking membership, we should always ask the collection rather than the item. E.g., we do `array.include?(item)` and never `item.contained_in?(array)`. 

---

Continuing on a tangent...

I think we should disable all Rubocop rules that can have different semantics. Rubocop is simply not equipped to know what the right solution should be. It's fine to Rubocop to indent code, add commas, or parentheses, or make sure that a class name fits the file name. However, it shouldn't be used to know which method to use. Another great backwards example is the `DynamicFinder` cop. Sometimes, your API will have `def find_by_id`, and it's not an `ActiveRecord`, so it shouldn't be replaced by `find_by(id:)`. If we used a linter that was aware of the types, we could pull this off, but Rubocop isn't aware of it, and IMO, shouldn't be used here.

**Comment by rafaelfranca** [comment]
I'm positive to this proposal. I had this problem a few times already.

About the tangent, I think we should evaluate case by case. The `Rails/DynamicFinder` which is not part of the styleguide is fine to disable in the app I know we are using it because that app uses sorbet and those dynamic methods are not going to be in the rbis. I'm not sure that will be the case of all other rules that have different semantics.

**Comment by volmer** [comment]
If I understood correctly, the proposition to not discourage `===` is because it is a better way to check hierarchy membership than `is_a?` or `kind_of?`. And the reason why it is better is because instances of `BasicObject` don't respond to `is_a?` or `kind_of?` but it does respond to `===`. I see a few problems with that:

* AFAIK instances of `BasicObject` don't respond to `===` either.
* In Objects, `===` is not a substitute for `is_a?` or `kind_of?`. The former is intended to be used for case statements while the latter is the actual method to check for superclasses.

> obj === other → true or false
Case Equality – For class Object, effectively the same as calling #==, but typically overridden by descendants to provide meaningful semantics in case statements.

> is_a?(class) → true or false
Returns true if class is the class of obj, or if class is one of the superclasses of obj or modules included in obj.

The reason why we discourage usage of `===` is because it is supposed to be called implicitly on case statements and not to be used for hierarchy checks.

**Comment by gmalette** [comment]
`BasicObject` is a class and responds to `===`, the instances are irrelevant.

**Comment by volmer** [comment]
> BasicObject is an instance of Class and responds to ===, the instances of BasicObject are irrelevant.

So if the point here is about `BasicObject` itself and not its instances then it also responds to `is_a?` and `kind_of?`.

**Comment by gmalette** [comment]
I don't understand what you mean here ^. 

To do the "typechecking" you don't call `instance === class`, you call `class === instance`. The fact that instances don't have `===` is irrelevant. The fact that instances don't have `is_a?` is very relevant.
